### ISSUE TITLE
How to access store created in file from another file?

### ISSUE THREAD

**Issue by jaguardo** [yezyilomo/state-pool#117]
For the simple case of the readme ```store```
how do we access the ```store``` created in this file form another file?

```
import { createStore } from 'state-pool';


const store = createStore();

const user = {
    name: "Yezy",
    age: 25,
    email: "yezy@me.com"
}
    
const profile = {
    url: "https://yezyilomo.me",
    rating: 5
}
store.setState("user", user);
store.setState("profile", profile);


function UserInfo(props){
    const [user, setUser, updateUser] = store.useState("user");
```

tried importing in the other file:
```
import { store} from "state-pool";
```

and setting it from within the function:
```
const [user, setUser, updateUser] = store.useState("user");
```
to no avail:
```
TypeError: state_pool__WEBPACK_IMPORTED_MODULE_7__.store is undefined
```

**Comment by yezyilomo** [comment]
Don’t import store from `state-pool`, just import the one you have created. The new API(Version >= 0.7) allows you to create a store yourself. A good way to use store in multiple components would be to create a `store.js` file, from there you create a store in it and export it so that you will be able use it in your components

```js
// store.js file
import { createStore } from 'state-pool';


const store = createStore();

// You can do some initializations here if you want

export { store };
```

Using a store in your component

```js
// Counter.js file
import React from 'react';
import { store } from 'store';  // importing store from store.js file


store.setState("count", 0); 

function Counter(props){
    const [count, setCount] = store.useState("count");

    // Other stuff 
}
```

If you want to use your store in another component you simply import it from `store.js` file, i.e

```js
import { store } from 'store'
```

**Comment by jaguardo** [comment]
Copy, works... how would you then subscribe to "count"?

**Comment by jaguardo** [comment]
Decent example of not updating: 
https://codesandbox.io/s/ffwre?file=/src/App.js

if you type something in the outlined box with "item one" selected it updates the input field, but it doesn't do the same on the others (item two and three), they do not trigger a re-render of the page... only when you select off and back on do you get the correct values...

not sure why it works for the 1 and not the other 2, but I"m trying to figure out how to trigger a re-render based on a change to the value

**Comment by yezyilomo** [comment]
This example has a bug here
```js
  const [inputValue, setInputValue, updateInputValue] = useGlobalState(
    `input${value}`
  );
```

It should be 

```js
  const [inputValue, setInputValue, updateInputValue] = useGlobalState(
    `input${index}`
  );
```
Replace  `input${value}` with  `input${index}`

**Comment by yezyilomo** [comment]
Someone made the same mistake here #87, your example is exactly the same as his.

**Comment by jaguardo** [comment]
thanks! I still have the same issue... I'm not getting the value updated, I'll see if I can reproduce... I have data that is displayed, but isn't being re-rendered when it changes.

**Comment by yezyilomo** [comment]
I just replaced `input${value}` with `input${index}` in your example and it worked fine.

Note in your example you’re using the old version of state-pool(v0.6.0 to be precise). The current version is 0.7.1, so make sure you’re not mixing up things.

Here is a working example for v0.7.1 for reference https://github.com/yezyilomo/state-pool-examples

**Comment by jaguardo** [comment]
that helps, thanks!
