### ISSUE TITLE
How to define initializeStore isn't in the documentation that I've been able to find

### ISSUE THREAD

**Issue by jaguardo** [yezyilomo/state-pool#129]
simply running
```store.remove("count", initializeStore)```
obviously causes a problem, as initializeStore isn't defined anywhere?

I tried creating it, something like this:
```
export const initializeStore = (name, value)=>{
  store.setState(name, value);
}
```
and then calling it this way
```store.remove(["count"], initializeStore("count", 0))```

and it doesn't fail, but the next use of `store.useState("count")` fails

**Comment by yezyilomo** [comment]
Checkout the new version(v0.8.0)
