### ISSUE TITLE
Don't throw if key is missing.

### ISSUE THREAD

**Issue by thewaver** [yezyilomo/state-pool#130]
What is the motivation for throwing if a certain key is missing?
I do not wish to pre-declare every single of my keys so that my code can be abstracted away from other logic.
Can't the store simply work as a native object? If key doesn't exist return `undefined` when reading, and add it when writing.
Am I missing something obvious here?

**Comment by yezyilomo** [comment]
You can use `default` argument to set a default value if the key is not predefined
