### ISSUE TITLE
state update doesn't trigger re-render

### ISSUE THREAD

**Issue by shiyuangu** [yezyilomo/state-pool#131]
Hi, 
   In the following code, the `C1` changes the state which is printed in another component `Login`.  I would expect the component `Login` to be re-rendered after `C1` changes the state. and hence output the `visible true`; However, it doesn't.  "Login" doesn't seem to be re-rendered  (or redraw) after the state changed.  It would work as expected if I wrap the state change with a `setTimeout`, that is,  `setTimeout(()=> showModal(true))`.  It would also work as expected if a regular `React.useState` replaced `store.useState`.   I wonder what causes this problem.  Can the fix of wrapping the state change with a `setTimeout` reliably force a re-rendered?  The code uses "state-pool 0.7.1" and "react 18.2.0".  Thank you! 

```js
import React, { useEffect, useLayoutEffect, useState } from 'react';
import { createStore } from 'state-pool';

const AuthContext = React.createContext();

const loginModalStore = createStore();
loginModalStore.setState('visible', false);

export function AuthProvider({ children }) {
  const [modalVisible, showModal] = loginModalStore.useState('visible');
  
  // const [modalVisible, showModal] = React.useState(false);
  
  return (
    <AuthContext.Provider value={{ showModal }} >
      {children}
      { <Login visible={ modalVisible } /> } 
    </AuthContext.Provider>
  );
}


function C1(){
  const { showModal } = React.useContext(AuthContext);
  useEffect( ()=> {
    showModal(true); // this doesn't work. 
    // setTimeout(()=> showModal(true)); // this will works. 
    console.log('set ShowModal');
  }, []);   
  return null;
};

function Login( {visible} ) {
  return (<div>
            { `visible ${visible}` } 
          </div>);
}

function App() {
  return (
    <AuthProvider>
      <C1 />
    </AuthProvider>
  );
}

export default App;
```

**Comment by yezyilomo** [comment]
Checkout the new version(v0.8.0)
