### ISSUE TITLE
Is 0.6.0 still usable?

### ISSUE THREAD

**Issue by malte94** [yezyilomo/state-pool#133]
I personally like the implementation approach of 0.6.0 much more than the current one.

Is version 0.6.0 still usable or does it contain any known bugs?

**Comment by yezyilomo** [comment]
Yes it is, but the implementation for the latest version is not much different from v0.6.0. What part of implementation did u like in v0.6.0?

**Comment by malte94** [comment]
@yezyilomo 

Thank you for your reply - and also for this cool library in general.

I just saw that using a store is not necessary. I would prefer continue using the hook "useGlobalState", which I obviously can.

**Comment by yezyilomo** [comment]
Yes, you can still use state-pool without store, in fact, `createGlobalState` and `useGlobalState` are the basic units of state-pool so they’ll always be supported plus store uses them too!.
