### ISSUE TITLE
Add proper documentation

### ISSUE THREAD

**Issue by alphaolomi** [yezyilomo/state-pool#92]
As part of  #hacktoberfest2021

Can we make some proper documentation 

Motivations: as the project grows i think it high time to dedicate some documentation to help new user and learn far more people in the process

1. @yezyilomo can you open a repo preferably called state-pool-docs  <small>(don't forget to make it hacktoberfest2021 eligible) </small>
2. I will personally push some personal notes i made as a start, i was thinking using  on something like Docusaurus  

Am open to thoughts and suggestions

**Comment by yezyilomo** [comment]
Documentation is now available on [yezyilomo.github.io/state-pool/](https://yezyilomo.github.io/state-pool/)
