### ISSUE TITLE
CUSTOM HOOK

### ISSUE THREAD

**Issue by soltrinox** [yezyilomo/state-pool#93]
**Yezileli Ilomo,**

Can you contact me ,  Hello I am Dylan Rosario i work in San Francisco.

 I have a PAID commision for you, and this component seems promising for a specific task i need.

 i would like you to create a CUSTOM hook from this state-pool LIB for me.

Specifically, i want and need to be able to access deep REACT-COMPONENTS  state  objects directly from the browser console. It should enforce to Reactive event / publisher  standards and force the subscriber state change handler event .

This means i can force hydration and push state changes  from the JS console at the browser level programmatically, with no mouse keyboard user input, . Which will fire off exactly as if a  browser were triggered by interaction.

The component should  probably provide a selector array of Objects and the respective states bound to the Objects. 
Most specifically, i need to update FORM INPUT Boxes, 

And YES this is a paid  $$$ commision of this LIB for my commercial use.  it will be distributed in a custom ISOMORPHIC Library i am releasing.  I have other solutions but i figured that since your a young man from a location not too unsimilar to  where my CEO comes from (  he was born and raised in Zanzibar) ,  So i figured i would give you a chance to makes some cash and possibly set up future dev work contracts.

Thanks In Advance. TIA,

Regards,
Dylan Rosario
dylan@rowzzy.com

**Comment by yezyilomo** [comment]
I think it’s doable, check your email.
