### ISSUE TITLE
Readme: setState() assignment

### ISSUE THREAD

**Issue by RichBernhardt** [yezyilomo/state-pool#94]
Hi Yezy, many thanks for this repo. Just one thing regarding the readme.
Key-based global state assignment has been consistently made with comma separator: 
`store.setState("user", initialGlobalState);`

...apart from one place - right above chapter: [useLocalState hook](https://github.com/yezyilomo/state-pool#uselocalstate-hook)
where a colon is used instead:
`store.setState("user": initialGlobalState);`

Is it deliberate or misspelling?

Cheers
Rich

**Comment by yezyilomo** [comment]
Thanks for pointing this out, it's definitely a typo, will fix it.
