### ISSUE TITLE
Server Side Rendering: This doesn't work with SSR

### ISSUE THREAD

**Issue by Lwdthe1** [yezyilomo/state-pool#95]
Just following up on the issue I commented on [your article on dev.to](https://dev.to/yezyilomo/server-side-rendering-ssr-with-state-pool-react-state-manager-14em) about SSR.

Thanks for making this package, it's wonderfully simple and effective. However, it is not well suited for SSR as it stands because the global state is shared across the NodeJs server, so all requests would share the same state.

A little more work is needed to make it work with SSR, but that entails creating a new store for each request and using the Context API & hooks to distribute that store to components that need to make use of the store. This also means the singleton store pattern has to be eliminated.

All throughout the code for the package, it's using the singleton that's exported. I already fixed the problem in a fork as I described above because I tested setting values on the store with the incoming request ID as the key during SSR from multiple browsers and saw that all the values were in the store across the requests.

As you can see in these files, the singleton `store` is being used by the hooks and they do not accept a store instance as an argument: 
* https://github.com/yezyilomo/state-pool/blob/2c1a889e7b0c529ec4aeb0497bd9fa5d379a2b10/src/useGlobalState.ts#L3
* https://github.com/yezyilomo/state-pool/blob/2c1a889e7b0c529ec4aeb0497bd9fa5d379a2b10/src/useGlobalStateReducer.ts#L25

<img width="1257" alt="Screen Shot 2021-11-21 at 9 31 45 PM" src="https://user-images.githubusercontent.com/5778798/142792567-cb7ea04b-72ef-45f3-b4cd-0af8292730f2.png">

I would be open to opening a Pull Request if I am not mistaking, so please let me know if I am.

**Comment by yezyilomo** [comment]
Thank you for following up, Sorry I couldn’t reply to your comment, didn’t get a time to test your issue, you can definitely open a PR, I’ll be happy to merge it if it adds that functionality. It’ll surely  help folks who are using SSR.

**Comment by yezyilomo** [comment]
Singleton store pattern has already been eliminated
