### ISSUE TITLE
Custom store object

### ISSUE THREAD

**Issue by bombillazo** [yezyilomo/state-pool#97]
This library looks super nice! One thing I was curious about was how feasible it would be to use persistence with a custom storage? Ive seen some libraries like React Query and Amplify expose an interface with set/get/clear methods so the library can handle persistence. Thanks for sharing this library!

**Comment by yezyilomo** [comment]
Thank you for pointing that out, I think it’s a good idea to have a general way to handle persistence so that people can use a storage of their choice. We are definitely going to implement a similar way for handling data persistence.
