### ISSUE TITLE
TypeScript useHook with generic type

### ISSUE THREAD

**Issue by bombillazo** [yezyilomo/state-pool#98]
Me again 😅

It would also be great to be able to type the data store, I'm thinking something like this perhaps?

```ts
 const [myValue] = useGlobalState<ValueType>('myValue');
```

Unless there is a way to infer type directly by associating the key and value used in the create/set function.

**Comment by bombillazo** [comment]
In fact, not just that hook but any other hook in the package.

**Comment by yezyilomo** [comment]
Yeah, I was thinking about this too, we’ll definitely add it.
